# Tomcat
#server:
 # port: 8486 #如需要启动 端口号，需确认端口没被占用，  当需要使用druid控制页面时可以启用端口
spring:
  aop:
    proxy-target-class: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.132.134.161:3306/hcjg?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Lizhensfroot
    initialSize: 10
    minIdle: 10
    maxActive: 200
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters
    filters: stat,wall,slf4j #,myFilter
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/
  #redis
  redis:
    database: 0
    host: localhost
    password:
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    local:
      host: localhost
#      host: 101.132.134.161
      port: 6379
  dubbo:
    application:
      name: lz-crm-provider
      id: lz-crm-provider-id
    server: true
    registry:
      address: zookeeper://127.0.0.1
      port: 2181
      #filter: dubboServiceFilter
    protocol:
      name: dubbo
      #port: 27893
      port: -1
    scan: com.lizhen.crm.biz.impl
    aop:
      proxy-target-class: true
      auto: true


lizhen:
  upload:
    prefix: lizhen/dealeroa
    remote:
      path: https://oa.lizhenauto.com/files/
    local:
      path: /wloa/jxsoa_files/
  download:
    file:
      remote:
        path: https://oa.lizhenauto.com/files/
      local:
        path: /wloa/jxsoa_files/

logging:
  file: ./logs/lizhen-crm.log
  level:
    com.*: debug


